name = "hep_lean"
defaultTargets = ["HepLean"]
# -- Optional inclusion for LeanCopilot
#moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.9.0"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.9.0"

[[lean_lib]]
name = "HepLean"

# -- Optional inclusion of tryAtEachStep
#[[require]]
#name = "tryAtEachStep" 
#git = "https://github.com/dwrensha/tryAtEachStep"
#rev = "main"

# -- Optional inclusion of LeanCopilot
#[[require]]
#name = "LeanCopilot"
#git = "https://github.com/lean-dojo/LeanCopilot.git"
#rev = "v1.2.2"

# lean_exe commands defined specifically for HepLean.

[[lean_exe]]
name = "check_file_imports"
srcDir = "scripts"

[[lean_exe]]
name = "type_former_lint"
srcDir = "scripts"
