name = "hep_lean"
defaultTargets = ["HepLean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "HepLean"

[[lean_exe]]
name = "check_file_imports"
srcDir = "scripts"
